// Vercel Insights
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";

// Wrapper & Theme Provider
import SuspenseWrapper from "@/components/SuspenseWrapper";
import { ThemeProvider } from "next-themes";

import { Footer } from "@/components/Layout/Footer";
import { Header } from "@/components/Layout/Header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <SuspenseWrapper>
            <Header />
            {children}
            <Analytics />
            <SpeedInsights />
            <Footer />
          </SuspenseWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
